### ISSUE TITLE
Error when launching example

### ISSUE THREAD

**Issue by Fraa-124** [ManuSekhon/mozilla-deepspeech-flutter#1]
Hello, I tried to run the example but it doesn't compile.

```
Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libdeepspeechlibc.so"
not found)
```
Do I have to do an intermediate build step or something? I just went to example folder, get packages and run it.

Thank you.

**Comment by geekruchika** [comment]
Hi @Fraa-124 
In which platform (iOS or Android) you tried to build?

**Comment by Fraa-124** [comment]
In Android emulator

**Comment by geekruchika** [comment]
> In Android emulator

Please try in the physical device.

**Comment by Fraa-124** [comment]
That's it. It works great on a physical device Thank you.
