### ISSUE TITLE
Spelling issues with transcription results

### ISSUE THREAD

**Issue by Mijawel** [ManuSekhon/mozilla-deepspeech-flutter#3]
Hi,

I understand this isn't something you are actively working on but I just thought I would ask anyway. I have installed this on flutter and it works really nicely pretty much out of the box (awesome stuff!). But the transcription has tons of spelling errors and I saw on this stackoverflow question that someone had a similar issue when the 'scorer' wasn't used.

https://stackoverflow.com/questions/64593694/mozilla-deep-speech-sst-suddenly-cant-spell

I was wondering if this is related and how I could fix it if so?

**Comment by manuindersekhon** [comment]
Hi @Mijawel, I am not working with deepspeech lib right now, but I searched about the misspellings problem. Yes, it seems like it can be improved by loading the scorer file that comes with the pretrained model.

I didn't add ffi interfaces to dart for the scorer functions at the time. If you have some experience in C and writing FFIs in dart, you can add [int DS_EnableExternalScorer(ModelState *aCtx, const char *aScorerPath)](https://deepspeech.readthedocs.io/en/latest/C-API.html#_CPPv423DS_EnableExternalScorerP10ModelStatePKc) function in c lib present in the repo, rebuild it, and include the updated binaries in flutter app. 

I am not sure if that will solve your exact problem, but above steps should be able to load the [scorer](https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.scorer) file and hopefully improve the accuracy.

**Comment by Mijawel** [comment]
Thanks so much for the tip. I'll give that a go. (you made a nice tutorial to go along with this repo so it does make it a lot easier).

**Comment by manuindersekhon** [comment]
HI @Mijawel, can you please confirm if scorer solved the issue, can we close this issue?

**Comment by Mijawel** [comment]
Sorry about the delay. I have just gotten to it now and after checking the scorer file at the link, I realised it's far too big to include within a mobile app at about 1gb.

Maybe it would be possible to train a more lightweight scorer file although I'm not too experienced with this and don't have the extra time to work it out at the moment.

Thanks for the tip though! Happy for you to close unless you or someone else wants to check it out.

**Comment by manuindersekhon** [comment]
Added scorer functions in PR https://github.com/ManuSekhon/mozilla-deepspeech-flutter/pull/4.
Closing this issue.
